const RADIUS_LOGIN_REGISTRATION_BOTTOM = 40.0;

const PADDING_HORIZONTAL_LOGIN_FIELDS = 20.0;
const PADDING_VERTICAL_LOGIN_FIELDS = 5.0;
const PADDING_HORIZONTAL_LOGIN_BOTTOM = 40.0;
const PADDING_VERTICAL_BUTTON = 8.0;

const FONT_SIZE_LOGIN_FIELDS = 20.0;
const FONT_SIZE_BUTTON = 40.0;
