// Radius
const RADIUS_LOGIN_REGISTRATION_BOTTOM = 40.0;
const RADIUS_LIST_ITEM = 5.0;

// Paddings
const PADDING_HORIZONTAL_LOGIN_FIELDS = 20.0;
const PADDING_VERTICAL_LOGIN_FIELDS = 5.0;
const PADDING_HORIZONTAL_LOGIN_BOTTOM = 40.0;
const PADDING_VERTICAL_LOGIN_BOTTOM = 40.0;
const PADDING_VERTICAL_BUTTON = 8.0;

// Font sizes
const FONT_SIZE_LOGIN_FIELDS = 20.0;
const FONT_SIZE_LOGIN_BOTTOM_OPTION = 18.0;
const FONT_SIZE_BUTTON = 40.0;

// Heights
const HEIGHT_PARKING_LIST_ITEM_IMAGE = 100.0;

// Widths
const WIDTH_PARKING_LIST_ITEM_IMAGE = 100.0;
