const LOGIN_REGISTRATION_BOTTOM_RADIUS = 40.0;
const LOGIN_FIELDS_PADDING_HORIZONTAL = 20.0;
const LOGIN_FIELDS_PADDING_VERTICAL = 5.0;
const LOGIN_BOTTOM_PADDING_HORIZONTAL = 30.0;

const LOGIN_FIELDS_TEXT_SIZE = 20.0;
